default:
  startup_wait: 90
  jetty_port: 8983
  java_opts:
    - "-Xmx512m"
    # pc: add options for jdk8, audit and oai 
    - "-XX:NewSize=256m"
    - "-XX:MaxNewSize=256m" 
    - "-XX:MetaspaceSize=256m"
    - "-XX:MaxMetaspaceSize=512m"
    - "-XX:+DisableExplicitGC"
    - "-Dfcrepo.audit.container=/audit"
    - "-Dfcrepo.data.container=/dev"